routes/index.py
import os
import uuid

import config
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
    current_app)
from werkzeug.datastructures import FileStorage

from models.message import send_mail
from models.reply import Reply
from models.topic import Topic
from models.user import User
# from routes import current_user, cache
from routes import current_user

import json

from utils import log

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""

import gevent
import time

ut = {}


@main.route("/")
def index():
    # t = threading.Thread()
    # t.start()
    gevent.spawn()
    time.sleep(0.5)
    print('time type', time.sleep, gevent.sleep)
    u = current_user()
    return render_template("login-page.html", user=u)


@main.route('/setting')
def setting():
    # form = request.form.to_dict()
    u = current_user()
    return render_template("setting.html", user=u)


@main.route('/setting_password', methods=['POST'])
def setting_password():
    form = request.form.to_dict()
    log('formmmm', form)
    # 用类函数来判断
    u = current_user()
    form['password'] = User.salted_password(form['newpassword'])
    u.update(u.id, password=form['password'])
    log('passzzz', u.password)
    return redirect(url_for('.index'))


@main.route('/setting_sgin', methods=['POST'])
def setting_sgin():
    form = request.form.to_dict()
    # 用类函数来判断
    u = current_user()
    log('username', u.username, u.sign)
    u.update(u.id, username=form['username'], sign=form['sign'])
    return redirect(url_for('.setting'))


@main.route("/register", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


@main.route("/register_view")
def register_view():
    return render_template("register_view.html")


@main.route("/reset/send", methods=['POST'])
def reset_send():
    form = request.form.to_dict()
    username = form['username']
    u = User.one(username=username)
    token = str(uuid.uuid4())
    ut[u.id] = token
    subject = '点击链接'
    author = config.admin_mail
    to = u.email
    content = 'http://localhost:3000/reset/view?token={}'.format(token)
    send_mail(subject, author, to, content)
    return render_template('index.html')


@main.route("/reset/view", methods=["GET", "POST"])
def reset_view():
    if 'token' not in request.args:
        return redirect(url_for('.index'))
    else:
        return render_template('reset_view.html', token=request.args['token'])


@main.route('/reset/update', methods=["POST"])
def reset_update():
    form = request.form.to_dict()
    log('ffff', form)
    for key in ut:
        if ut[key] == form['token']:
            u = User.one(id=int(key))
            form['password'] = u.salted_password(form['newpassword'])
            log('ppppp', form['password'], form['newpassword'])
            u.update(u.id, password=form['password'])
    return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    log('passaaaaa', form, u)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        # session_id = str(uuid.uuid4())
        # key = 'session_id_{}'.format(session_id)
        # log('index login key <{}> user_id <{}>'.format(key, u.id))
        # cache.set(key, u.id)

        # redirect_to_index = redirect(url_for('topic.index'))
        # response = current_app.make_response(redirect_to_index)
        # response.set_cookie('session_id', value=session_id)
        # 转到 topic.index 页面
        # return response
        session['user_id'] = u.id
        return redirect(url_for('topic.index'))


def created_topic(user_id):
    # O(n)
    ts = Topic.all(user_id=user_id)
    return ts
    #
    # k = 'created_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     ts = Topic.all(user_id=user_id)
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #     return ts


def replied_topic(user_id):
    # O(k)+O(m*n)
    rs = Reply.all(user_id=user_id)
    ts = []
    for r in rs:
        t = Topic.one(id=r.topic_id)
        ts.append(t)
    return ts
    #
    #     sql = """
    # select * from topic
    # join reply on reply.topic_id=topic.id
    # where reply.user_id=1
    # """
    # k = 'replied_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     # ts = Topic.select()
    #     #   .join(Reply, 'id', 'topic_id')
    #     #   .where(user_id=user_id)
    #     #   .all()
    #     rs = Reply.all(user_id=user_id)
    #     ts = []
    #     for r in rs:
    #         t = Topic.one(id=r.topic_id)
    #         ts.append(t)
    #
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #
    #     return ts


@main.route('/profile')
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    if suffix not in ['gif', 'jpg', 'jpeg']:
        abort(400)
        log('不接受的后缀, {}'.format(suffix))
    else:
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        path = os.path.join('images', filename)
        file.save(path)

        u = current_user()
        User.update(u.id, image='/images/{}'.format(filename))

        return redirect(url_for('.setting'))


@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:3000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/delete")
@csrf_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST", "GET"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="注册">
        </div>
    </form>
    <form class="form-horizontal" method="post" action="{{ url_for('index.login') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="登录">
        </div>
    </form>
<form class="form-horizontal" method="post" action="{{ url_for('index.reset_send') }}">
     <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
     </div>
    <div class="form-actions">
        <input type="submit" class="span-primary" value="更改密码">
    </div>
</form>
        </div>
    </div>
</body>
</html>

templates/login-page.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="static/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="static/assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>Login Page - Now UI Kit by Creative Tim</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="static/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="static/assets/css/now-ui-kit.css?v=1.1.0" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="static/assets/css/demo.css" rel="stylesheet" />
    <!-- Canonical SEO -->
    <link rel="canonical" href="" />
    <!--  Social tags      -->
    <meta name="keywords" content="">
    <meta name="description" content="">



</head>

<body class="login-page sidebar-collapse">
    <!-- End Navbar -->
    <div class="page-header" filter-color="orange">
        <div class="page-header-image" style="background-image:url(../static/assets/img/bg4.jpg)"></div>
        <div class="container">
            <div class="col-md-4 content-center">
                <div class="card card-login card-plain">
                    <form class="form" method="post" action="{{ url_for('index.login') }}">
                        <div class="header header-primary text-center">
                            <div class="logo-container">
                                <img src="static/assets/img/logo.jpg" alt="">
                            </div>
                        </div>
                        <div class="content">
                            <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons users_circle-08"></i>
                                </span>
                                <input type="text" class="form-control" placeholder="username" name="username" value="admin">
                            </div>
                            <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons text_caps-small"></i>
                                </span>
                                <input type="text"  class="form-control" placeholder="password" name="password" value="admin">
                            </div>
                        </div>
                        <div class="footer text-center">
							<input type="submit" class="btn btn-primary btn-round btn-lg btn-block" value="登录">
                        </div>
{#                        <div class="form-actions">#}
{#							<input type="submit" class="btn btn-primary btn-round btn-lg btn-block" value="登录">#}
{#						</div>#}
                        </form>
                        <div class="pull-left">
                            <h6>
                                <a href="{{ url_for('index.register_view') }}" >注册</a>
                            </h6>
                        </div>
                        <div class="pull-right">
                            <h6>
                                <a href="{{ url_for('index.setting') }}" >修改密码</a>
                            </h6>
                        </div>
                </div>
            </div>
        </div>

    </div>
</body>
<!--   Core JS Files   -->
<script src="static/assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="static/assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="static/assets/js/plugins/bootstrap-switch.js"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="static/assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="static/assets/js/plugins/bootstrap-datepicker.js" type="text/javascript"></script>
<!-- Share Library etc -->
<script src="static/assets/js/plugins/jquery.sharrre.js" type="text/javascript"></script>
<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="static/assets/js/now-ui-kit.js?v=1.1.0" type="text/javascript"></script>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>

</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
<h1>用户资料页面</h1>
<div>
    {{ user.id }}
</div>
<div>
    {{ user.username }}
</div>

<div>
    <div>创建的</div>
    {% for t in created %}
        <a href="{{ url_for('topic.detail', id=t.id) }}">{{ t.title }}</a>
    {% endfor %}
</div>
<div>
    <div>参与的</div>
    {% for t in replied %}
        <a href="{{ url_for('topic.detail', id=t.id) }}">{{ t.title }}</a>
    {% endfor %}
</div>

<form method="post"
      action="{{ url_for('.avatar_add')}}"
      enctype="multipart/form-data"
>
    <input type="file" name="avatar">
    <button type="submit">上传头像</button>
</form>

<img src="{{ user.image }} ">

</body>
</html>

templates/register_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs 注册</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <form class="form-horizontal" method="post" action="{{ url_for('.register') }}">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="注册">
        </div>
    </form>
</body>
</html>

templates/reset_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>重置密码</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<form class="form-horizontal" method="post" action="{{ url_for('index.reset_update') }}">
        <div class="control-group">
            <label class="control-label">密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="newpassword">
                <input type="hidden" name="token" value="{{ token }}">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="确定">
        </div>
    </form>
</body>
</html>

templates/setting.html
{% extends "topic/base.html" %}
{% block title %}修改个人信息{% endblock%}
{% block main %}
    <div id="sidebar">
    <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar">
                            <img src="{{ user.image }} ">
                        </a>
                        <span class="user_name">
                            <a class="dark">{{ user.username }}</a>
                        </span>

                        <div class="space clearfix"></div>
                        <span class="signature">
                             <a class="dark">{{ user.sign }}</a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>


<form class="form-horizontal" method="post" action="{{ url_for('index.setting_sgin') }}">
    <div class="control-group">
        <label class="control-label">用户名</label>
        <div class="controls">
            <input type="text" class="input-xlarge" name="username">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">个性签名</label>
        <div class="controls">
            <input type="text" class="input-xlarge" name="sign">
        </div>
    </div>
    <div class="form-actions">
        <input type="submit" class="span-primary" value="保存设置">
    </div>
</form>
<form class="form-horizontal" method="post" action="{{ url_for('index.setting_password') }}">
    <div class="control-group">
        <label class="control-label">当前密码</label>
        <div class="controls">
            <input type="text" class="input-xlarge" name="password">
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">新密码</label>
        <div class="controls">
            <input type="text" class="input-xlarge" name="newpassword">
        </div>
    </div>
    <div class="form-actions">
        <input type="submit" class="span-primary" value="更改密码">
    </div>
</form>
    <form class="form-horizontal " method="post"
          action="{{ url_for('index.avatar_add') }}"
          enctype="multipart/form-data"
    >
        <input type="file" name="avatar">
        <button type="submit">上传头像</button>
    </form>

{#<img src="{{ user.image }} ">#}

{% endblock %}